language: emacs-lisp
sudo: no
env:
# AFAICT, emacs 24.1 and 24.2 shouldn't work
 - EVM_EMACS=emacs-24.1-travis
 - EVM_EMACS=emacs-24.2-travis
 - EVM_EMACS=emacs-24.3-travis
 - EVM_EMACS=emacs-24.4-travis
 - EVM_EMACS=emacs-24.5-travis
 - EVM_EMACS=emacs-25.1-travis
 - EVM_EMACS=emacs-25.2-travis
 - EVM_EMACS=emacs-25.3-travis
 - EVM_EMACS=emacs-26.1-travis
# - EVM_EMACS=emacs-git-snapshot-travis
install:
  - export PATH="$HOME/.evm/bin:$PATH"
  - export PATH="$HOME/.cask/bin:$PATH"
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
script:
  - cask install
  - cask exec ert-runner
